baseURL = "https://minsblog.github.io/"
languageCode = "ko-kr"
theme = "PaperMod"

enableRobotsTXT = true

defaultContentLanguage = "ko"

[languages.en]
title = "MINLOG"

[languages.en.params]
dateFormat = "Jan 2, 2006"

[languages.en.menu]
main = [
{ name = "Archives", url = "archives", weight = 1 },
{ name = "Tags", url = "tags", weight = 2 },
{ name = "Search", url = "search", weight = 3 },
]

[languages.ko]
title = "MINLOG"

[languages.ko.params]
dateFormat = "2006년 1월 2일"

[languages.ko.menu]
main = [
{ name = "아카이브", url = "archives", weight = 1 },
{ name = "태그", url = "tags", weight = 2 },
{ name = "검색", url = "search", weight = 3 },
]

[outputs]
home = ["HTML", "RSS", "JSON"]

[params]
title = "MINLOG"
description = "Bubbler's dev stories"
keywords = ["MIN9", "Node.js", "Mathematics", "Problem Solving"]
author = "MIN9"
social = true
socialIcons = [
{ name = "github", url = "https://github.com/min-9" },
{ name = "instagram", url = "https://instagram.com/min9.exe" }
]
defaultTheme = "auto"
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
ShowToc = true
math = true
comments = true

[params.homeInfoParams]
Title = "Moments of Inspiration, Navigating Logs"

[params.assets]
disableHLJS = true

[menu]
main = [
{ name = "Archives", url = "archives" },
{ name = "Search", url = "search" },
]
